/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_LedRed_aliases.h"
#include "Pin_LedRed.h"
#include "Pin_LedGreen_aliases.h"
#include "Pin_LedGreen.h"
#include "Pin_LedYellow_aliases.h"
#include "Pin_LedYellow.h"
#include "Pin_Button1_aliases.h"
#include "Pin_Button1.h"
#include "Pin_Button2_aliases.h"
#include "Pin_Button2.h"
#include "Pin_Button3_aliases.h"
#include "Pin_Button3.h"
#include "Pin_Button4_aliases.h"
#include "Pin_Button4.h"
#include "ISR_Button1.h"
#include "ISR_Button2.h"
#include "ISR_Button3.h"
#include "ISR_Button4.h"
#include "Pin_Seg1_A_aliases.h"
#include "Pin_Seg1_A.h"
#include "Pin_Seg1_B_aliases.h"
#include "Pin_Seg1_B.h"
#include "Pin_Seg1_C_aliases.h"
#include "Pin_Seg1_C.h"
#include "Pin_Seg1_D_aliases.h"
#include "Pin_Seg1_D.h"
#include "Pin_Seg1_E_aliases.h"
#include "Pin_Seg1_E.h"
#include "Pin_Seg1_F_aliases.h"
#include "Pin_Seg1_F.h"
#include "Pin_Seg1_G_aliases.h"
#include "Pin_Seg1_G.h"
#include "Pin_Select_aliases.h"
#include "Pin_Select.h"
#include "Pin_Display_aliases.h"
#include "Pin_Display.h"
#include "Control_Reg_SevenSegmentLED.h"
#include "UART_1.h"
#include "SYStick.h"
#include "ISR_SYStick.h"
#include "Clock_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

