/*
 * $Name/$_type.cpp
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated
 */



#include "$Name/$_type.h"

extern "C"
{

RC_t $NAME/$_scaleR2D( const $Type_raw/$ * const praw, $Type_app/$ * const pvalue)
{
#error "Enter your code here"
	return RC_ERROR;
}

RC_t $NAME/$_scaleD2R( const $Type_app/$ * const pvalue, $Type_raw/$ * const praw)
{
#error "Enter your code here"
	return RC_ERROR;
}

} //extern  "C"
