/*
 * $Name/$_type.h
 *
 *  Created on: 01.05.2016
 *      Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm, 2016
 */



#ifndef $NAME/$_TYPE_H_
#define $NAME/$_TYPE_H_

#include "global.h"

/*****************************************************************************************
 *************** Type Definition for $NAME/$ signal                     **************************
 *****************************************************************************************/

#error "Provide a sensible data structure"

typedef struct
{
	...YOURDATA
} $Type_app/$;

#error "Provide a sensible init value"
#define $NAME/$_INIT_DATA (($NAME/$_data_t){0})



#endif /* SWC_ENGINE_TYPE_H_ */

