/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ErikaOS_ee.h"
#include "UART_LOG.h"
#include "BUTTON_2_aliases.h"
#include "BUTTON_2.h"
#include "BUTTON_1_aliases.h"
#include "BUTTON_1.h"
#include "isr_BUTTON.h"
#include "S7D_SegmentA_aliases.h"
#include "S7D_SegmentA.h"
#include "S7D_SegmentB_aliases.h"
#include "S7D_SegmentB.h"
#include "S7D_SegmentC_aliases.h"
#include "S7D_SegmentC.h"
#include "S7D_SegmentD_aliases.h"
#include "S7D_SegmentD.h"
#include "S7D_SegmentE_aliases.h"
#include "S7D_SegmentE.h"
#include "S7D_SegmentF_aliases.h"
#include "S7D_SegmentF.h"
#include "S7D_SegmentG_aliases.h"
#include "S7D_SegmentG.h"
#include "S7D_Select_aliases.h"
#include "S7D_Select.h"
#include "S7D_Display_aliases.h"
#include "S7D_Display.h"
#include "S7D_ControlReg.h"
#include "PWM_Red.h"
#include "PWM_CLK.h"
#include "PWM_Green.h"
#include "PWM_Blue.h"
#include "RGB_B_aliases.h"
#include "RGB_B.h"
#include "RGB_G_aliases.h"
#include "RGB_G.h"
#include "RGB_R_aliases.h"
#include "RGB_R.h"
#include "LED_Red_aliases.h"
#include "LED_Red.h"
#include "LED_Green_aliases.h"
#include "LED_Green.h"
#include "LED_Yellow_aliases.h"
#include "LED_Yellow.h"
#include "UART_LOG_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

